---
# ansible-playbook ./plugset.yml
- name: Set Plug States
  hosts: wti_pdu
  connection: local
  gather_facts: false

  tasks:
    - set_fact: use_https=True
      when: use_https is undefined
    - set_fact: validate_certs=True
      when: validate_certs is undefined
    - name: run Set Plug States (reboot plugs 1 and 2)
      cpm_plugcontrol:
        cpm_action: "setplugcontrol"
        cpm_url: "{{ansible_host}}"
        cpm_username: "{{ansible_user}}"
        cpm_password: "{{ansible_pw}}"
        plug_id: "1,2"  # plugs 1 and 2 are being changed
        plug_state: "boot"
        use_https: "{{use_https}}"
        validate_certs: "{{validate_certs}}"

      register: testout
    - name: dump test output
      vars:
            datacount: "{{ testout['data']['plugdatacount']  }}"
      debug:
#        with_items: testout.results
#        msg: "{{ testout['changed'] }}"
#        msg: "{{ testout['data']['plugdatacount'] }}"
        msg: "{{ datacount }}"
#        msg: "{{ testout['data']['powerplugs'][0]['plugname'] }}"
#      loop: “{{ testout['data'] }}”

    - name: Fail if return code is not 0
      debug:
        msg: "{{item.current}}"
#      fail:
#          msg: "The command  did not have a 0 return code"
      when: 0 != {{item.current}}
      loop: "{{ testout.data.powerplugs }}"
