---
# ansible-playbook ./getverlookup.yml
- name: Get Device Firmware version
  hosts: wti_pdu
  connection: local
  gather_facts: False

  tasks:
    - set_fact: use_https=True
      when: use_https is undefined
    - set_fact: validate_certs=True
      when: validate_certs is undefined

    - name: run Get Device Status
      debug:
        var: lookup('cpm_status',
                  'firmware',
                  validate_certs=validate_certs,
                  use_https=use_https,
                  cpm_url=ansible_host,
                  cpm_username=ansible_user,
                  cpm_password=ansible_pw,
                  wantlist=True)

      register: var1

      when:
          - 1 == 1

#    - debug: output_1=var.stdout_lines

    - name: dump JSON output
      debug:
        msg: "{{ var1 }}"
#        msg: "{{ var1['lookup('cpm_status', 'firmware', validate_certs=validate_certs, use_https=use_https, cpm_url=ansible_host, cpm_username=ansible_user, cpm_password=ansible_pw)'] }}"
#      loop: “{{ var1.changed }}”

#    - name: Goof Around
#      when: version_outout.stdout.find('code') != -1
