# ansible-playbook ./port_config.yml
- name: Set Network Interface  parameters
  hosts: wti_159
  connection: local
  gather_facts: False

  tasks:
  - set_fact: use_https=True
    when: use_https is undefined
  - set_fact: validate_certs=True
    when: validate_certs is undefined

  - name: run Set Time Date parameters
    cpm_interface_config:
      cpm_url: "{{ansible_host}}"
      cpm_username: "{{ansible_user}}"
      cpm_password: "{{ansible_pw}}"
      interface: "eth0"
#      enable: 0
      ipv4netmask: "255.255.255.0"
      ipv4gateway: "192.168.0.1"
      ipv4address: "192.168.0.159"
#      ipv4dhcpenable: 1
#      ipv4dhcphostname: hostname
#      ipv4dhcplease: 98
#      ipv4dhcpobdns: 97
#      ipv4dhcpupdns: 96
#      ipv6address: "ee:77:57:53"
#      ipv6gateway: "ff:ff:ff:ee::"
#      ipv6netmask: "64"
      use_https: "{{use_https}}"
      validate_certs: "{{validate_certs}}"

    register: testout
  - name: dump test output
    debug:
      msg: "{{ testout['data'] }}"
