# ansible-playbook ./port_config.yml
- name: Set Time Date parameters
  hosts: wti_169
  connection: local
  gather_facts: False

  tasks:
  - set_fact: use_https=False
    when: use_https is undefined
  - set_fact: validate_certs=False
    when: validate_certs is undefined

  - name: run Set Time Date parameters
    cpm_time_config:
      cpm_url: "{{ansible_host}}"
      cpm_username: "{{ansible_user}}"
      cpm_password: "{{ansible_pw}}"
#      date: "10/12/2019"
#      time: "11:38:46"
      timezone: 5
      ntpenable: 1
      ipv4address: "1.2.3.4,"
      ipv6address: ","
      timeout: 2
      use_https: "{{use_https}}"
      validate_certs: "{{validate_certs}}"

    register: testout
  - name: dump test output
    debug:
      msg: "{{ testout['data'] }}"
